import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Rubik } from "next/font/google";


import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import ReduxProviders from "@/providers/ReduxProvider";
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-rubik",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KICKS",
  description: "Generated by KICKS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} antialiased`}
       suppressHydrationWarning>
        <ReduxProviders >
          <Navbar></Navbar>
          <AntdRegistry>{children}</AntdRegistry>
          <Footer></Footer>
        </ReduxProviders>
      </body>
    </html>
  );
}
